### ISSUE TITLE
"Open Cypress" link not visible, so not working - Cypress V10.2.0

### ISSUE THREAD

**Issue by siglp** [Shelex/vscode-cy-helper#11]
**Describe the bug**
"Open Cypress" link not visible with Cypress v10 (old helper version shows it, but not run)

**To Reproduce**

1. Open VS Code
2. Open file with test
3. No "Open Cypress" len above test

**Expected behavior**
"Open Cypress" etc. visible as it was in old version.

**Environment (please complete the following information):**

-   Extension version: v2.5.0
-   VS Code version: 1.68.1
-   OS: Windows | Mac | Linux (distro): Linux Mint 20.1 Cinnamon

** Developer Tools Console Output **

In console I do not see nothing.

**Additional context**

![Screenshot from 2022-06-25 13-04-00](https://user-images.githubusercontent.com/4044395/175770768-75e0ed0d-981d-41dd-a427-422b1a4bc965.png)

![Screenshot from 2022-06-25 13-06-36](https://user-images.githubusercontent.com/4044395/175770867-4d7615d9-fb54-46b1-94e0-2df64560ea4a.png)

**Comment by tnrich** [comment]
Can confirm also hitting this bug. This was the only feature I used this extension for. Please fix 🙏 

Thanks!
