### ISSUE TITLE
Type Definition on Save not working from version 2.6.0

### ISSUE THREAD

**Issue by TheKolega** [Shelex/vscode-cy-helper#16]
**Describe the bug**
From version 2.6.0 onward the cypressHelper.typeDefinitionOnSave setting is not working and the customCommands.d.ts file is not updated after saving the commands.js file

**To Reproduce**
- Use vscode-cy-helper latest version 
- Set cypressHelper.typeDefinitionOnSave to true
- Make an edit in the commands.js file and save it
- Notice the customCommands.d.ts isn't changed and the file generation wasn't triggered on save

**Expected behavior**
A VSCode notification appears and the customCommands.d.ts file is updated with new definitions

**Environment (please complete the following information):**

-   Extension version: 2.6.0
-   VS Code version: 1.70.1
-   OS: Linux (Ubuntu)

**Additional context**
When triggering the `Cypress: Generate Custom Command Types` option via the Command Palette it works just fine

**Comment by Shelex** [comment]
Thanks for reporting!
Fixed in v3.2.0
