### ISSUE TITLE
Non-default file patterns aren't recognized by the `cypressCodeLensePattern` setting

### ISSUE THREAD

**Issue by adamalston** [Shelex/vscode-cy-helper#17]
**Describe the bug**

Code lenses aren't shown in files with non-default file extensions.

**To Reproduce**

1. Create a test file with a filename `testfile.spec.tsx`
2. Create another test file with a filename `testfile.spec.ts`
3. Add the following test to both files
```tsx
  it('testing file patterns', () => {
    cy.get('html').then(() => {});
  });
```
4. By default, the test in the `ts` file should have lenses, the one in the `tsx` file should not
5. Change the `cypressHelper.cypressCodeLensePattern` setting to `"**/cypress/**/*.{js,jsx,ts,tsx}"`
6. The tests in both files should show lenses now, however, the one in the `tsx` does not

**Expected behavior**

The tests in both files should show lenses.

**Environment (please complete the following information):**

-   Extension version: 3.2.0
-   VS Code version: 1.73.0
-   OS: Windows | Mac | Linux (distro): Mac

** Developer Tools Console Output **

**Comment by Shelex** [comment]
Hi @adamalston 
Thanks for opening an issue!

Indeed, plugin activates just for javascript and typescript languages. 
VS Code treats `.tsx` and `.jsx` files as separate languages (`typescriptreact` and `javascriptreact`).

Activation events for both are provided in extension v3.3.0.
