### ISSUE TITLE
No menu item for 'Clear ".skip"'

### ISSUE THREAD

**Issue by adamalston** [Shelex/vscode-cy-helper#18]
**Describe the bug**
I can 'Set ".only"', 'Set ".skip"', and 'Clear ".only"' from the menu. However, there is no menu items to clear the ".skip".

**To Reproduce**

1. Set the `ItSkip` option to `true` in the `menuItems` setting:
    ```json
    {
      "OpenCypress": true,
      "RunCypress": false,
      "ItOnly": true,
      "ItSkip": true,
      "GenerateCustomCommandTypes": true,
      "GoToCustomCommand": true,
      "FindCustomCommandReferences": true,
      "FindStepDefinitionReferences": true,
      "SchemaGenerator": true
    }
    ```
3. Reload the extension
4. In the menu for a test, click 'Set ".skip"'
5. Notice that there is no option to clear the ".skip" after it has been set

**Expected behavior**

I expected an option to clear the ".skip" to show up in the menu.

**Environment (please complete the following information):**

-   Extension version: 3.3.0
-   VS Code version: 1.73.1
-   OS: macOS

**Comment by Shelex** [comment]
Hi @adamalston !
Thank you for opening an issue.

The fix is released in v3.3.1, you should get an update soon.
