### ISSUE TITLE
Alias autocompletion is not working with cy.wait

### ISSUE THREAD

**Issue by ark-key** [Shelex/vscode-cy-helper#19]
**Describe the bug**
Alias autocompletion is not working with **cy.wait**

**To Reproduce**
1. create an alias with **as** for **cy.intercept**, for example:
`cy.intercept('POST', '*/create').as('createRequest')`
3. use **cy.wait**:
`cy.wait('@createRequest')`
4. see autocompletion is not working while typing the alias

**Expected behavior**
Alias autocompletion is working with cy.wait

**Environment (please complete the following information):**

-   Extension version: 3.3.0
-   VS Code version: 1.73.1
-   OS: Ubuntu 20.04

**Developer Tools Console Output:** It is empty

**Additional context:** Alias autocompletion is working with **cy.get**

**Comment by Shelex** [comment]
Hi @ark-key !
Thank you for opening an issue.

Support for alias autocomplete for `cy.wait` is published in v3.3.1, you should get an update soon.

**Comment by ark-key** [comment]
It works. Many thanks)
