### ISSUE TITLE
More options to '.only' or '.skip' for more Mocha keywords

### ISSUE THREAD

**Issue by jdvegmond** [Shelex/vscode-cy-helper#20]
**Is your feature request related to a problem? Please describe.**
When writing tests I sometimes would like to run them only for a specific 'describe' or 'context' part of my code or I want to specifically skip them.

**Describe the solution you'd like**
Would it be possible to show the "Open Cypress | Set ".only" " for the Mocha keywords 'describe' and 'context' as well?
And I'm sure there was a time when it was also possible to ".skip" tests, but nowadays I don't see that anymore.

**Additional context**
In https://github.com/Shelex/vscode-cy-helper/issues/4 the '.only' addition was done only for the 'specify' keyword.

**Comment by Shelex** [comment]
Hi @jdvegmond 
Thank you for opening an issue.
Added support for `describe` and `context` keywords as well.
