### ISSUE TITLE
'undefined' appended to autogenerated command type

### ISSUE THREAD

**Issue by FranciscoKnebel** [Shelex/vscode-cy-helper#21]
**Describe the bug**
Auto generating types for commands appends `undefined` to variable name in customCommands.d.ts if a type is set for the variable in the command.

Not setting a type for the variables does not append `undefined`.

![image](https://user-images.githubusercontent.com/10299622/221234529-4ea21de3-2cda-4cd9-8e81-d532883bec6e.png)

![image](https://user-images.githubusercontent.com/10299622/221234264-32faafe9-3bc9-42e7-a490-081757814cae.png)

**To Reproduce**

1. Create a command with typed inputs
2. Check customCommands.d.ts for generated command.

**Expected behavior**

Expected `example_command_name(type : string, value : number): Chainable<any>;`

**Environment (please complete the following information):**

-   Extension version: 3.3.1
-   VS Code version: 1.75.1
-   OS: Windows | Mac | Linux (distro): Windows 11, via Ubuntu WSL

** Developer Tools Console Output **

Nothing on console output.

**Additional context**

No further context needed.

**Comment by Shelex** [comment]
Hi @FranciscoKnebel 
Thank you for opening an issue.

Resolved in v3.5.0
