### ISSUE TITLE
Tab size in customcommands.d.ts is always 4

### ISSUE THREAD

**Issue by jdvegmond** [Shelex/vscode-cy-helper#22]
When the customcommands.d.ts file is created, indentations are always size 4, even when a different size is set in the VSC settings. Is it possible to change this? Maybe add a Cypress helper setting for this?

**Comment by Shelex** [comment]
Hi @jdvegmond 
Thank you for opening an issue.

Resolved in v3.5.0, now it will check root editor tab size and prettier tab size, and return the value based on default formatter for specific file type.
