### ISSUE TITLE
Error m.includes when generating the Type Definition File

### ISSUE THREAD

**Issue by filiperangel** [Shelex/vscode-cy-helper#23]
Hi,

sorry if I am creating this in the wrong place but I couldn't find anywhere to ask questions.

I am having an issue when I am trying to save my commands file, it shows an error on the extension.

![image](https://github.com/Shelex/vscode-cy-helper/assets/16592442/e594f2e7-fee4-4911-bc63-a9a4ad6ef0e6)

Opening the Developer Tools I see this:

![image](https://github.com/Shelex/vscode-cy-helper/assets/16592442/e3da6774-a451-49c8-802f-6a618eb340d8)
![image](https://github.com/Shelex/vscode-cy-helper/assets/16592442/bdb9e31a-116b-4c3d-a3c6-b6f698edc015)

My extension settings are like this:

![image](https://github.com/Shelex/vscode-cy-helper/assets/16592442/0c00412f-b39f-4c27-9082-75110f21f9ef)

![image](https://github.com/Shelex/vscode-cy-helper/assets/16592442/e73bbb28-63dd-4c3f-b094-ae4e24558662)

It worked for some time then started crashing.

I also did a complete clear of VSCode and installed the extension again, which started to work for some time but then I ran into the same issue as above.

Could you please let me know if you have seen this issue before and how I could fix it?

I am happy to provide more information if I missed anything.

Thanks

**Comment by Shelex** [comment]
Should be resolved with latest version.
