### ISSUE TITLE
Optional Mocha keywords for test should have the same effect as default test words like "it"

### ISSUE THREAD

**Issue by BryanHoffmaster** [Shelex/vscode-cy-helper#4]
**Is your feature request related to a problem? Please describe.**
MacOS : 12 Big Sur
VSCode: Version: 1.63.2 (Universal)
Using Latest Cypress Helper V2 extension loaded from Marketplace

When I use "specify" instead of "it" to start a test, the text that hovers above the test that shows "Open Cypress | Set ".only" " does not show. 

**Describe the solution you'd like**
Would it be possible to show the "Open Cypress | Set ".only" " for all Mocha keywords for tests?

**Additional context**
The work around right now is just to change it from "specify" to "it" for a second then I can open the test file directly

**Comment by Shelex** [comment]
Released in 2.5.0
